export default function ProofSection() {
  return (
    <section className="proof-section">
      <div className="proof-grid">
        <div className="proof-card fade-up">
          <div className="number">3,000+</div>
          <div className="label">Businesses Helped</div>
        </div>
        <div className="proof-card fade-up delay-1">
          <div className="number">$1M+</div>
          <div className="label">Revenue Generated by 18</div>
        </div>
        <div className="proof-card fade-up delay-2">
          <div className="number">10K+</div>
          <div className="label">People Coached</div>
        </div>
        <div className="proof-card fade-up">
          <div className="number">280+</div>
          <div className="label">Digital Products Developed</div>
        </div>
        <div className="proof-card fade-up delay-1">
          <div className="number">48+</div>
          <div className="label">Countries Served</div>
        </div>
        <div className="proof-card fade-up delay-2">
          <div className="number">20+</div>
          <div className="label">Fortune 500 Companies Helped</div>
        </div>
      </div>
    </section>
  );
}
